<?php

########################################################################
# Extension Manager/Repository config file for ext: "googlemapsapi"
#
# Auto generated by Extension Builder 2014-04-24
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google Maps API',
	'description' => '',
	'category' => 'misc',
	'author' => 'Michael Grundkötter',
	'author_email' => 'mg@ujamii.com',
	'author_company' => 'ujamii',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>